
services:
  vju_chatbot:
    build:
      context: .
      dockerfile: ./VJU_chatbot/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - rasa-server
      - rasa-actions-server
      - rag-server
      - duckling-server

  rag-server:
    build:
      context: .
      dockerfile: ./Rag/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./Rag/data_source:/app/data_source
      - ./Rag/src:/app/src

  rasa-server:
    build:
      context: .
      dockerfile: ./Rasa/Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./rasa/actions:/app/actions
      - ./rasa/data:/app/data
    depends_on:
      - duckling-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/version"]
      interval: 10s
      timeout: 5s
      retries: 5

  rasa-actions-server:
    build: 
      context: .
      dockerfile: ./Rasa/Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./rasa/actions:/app/actions
      - ./rasa/utils:/app/utils
    depends_on:
      - rasa-server

  duckling-server:
    image: rasa/duckling:latest
    ports:
      - "8000:8000"