[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#1C1C1C"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#1A1A1A"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"