services:

  duckling-server:
    image: rasa/duckling:latest
    ports:
      - 8000:8000
    networks:
      - all

  rasa-server:
    build: .
    image: my-rasa-bot:latest # Thay đổi thành tên image của bạn
    working_dir: /app
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./actions:/app/actions
      - ./data:/app/data
      - ./utils:/app/utils
      - ./models:/app/models # Thêm volume cho model để không bị xóa
    ports:
      - 5005:5005
    networks:
      - all


networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"